#define REDIS_GIT_SHA1 "c33529dc"
#define REDIS_GIT_DIRTY "      69"
#define REDIS_BUILD_ID "gim-yelim-ui-MacBookPro.local-1715130095"
#include "version.h"
#define REDIS_BUILD_ID_RAW SERVER_NAME VALKEY_VERSION REDIS_BUILD_ID REDIS_GIT_DIRTY REDIS_GIT_SHA1
