#define REDIS_GIT_SHA1 "bcaa2a4c"
#define REDIS_GIT_DIRTY "      68"
#define REDIS_BUILD_ID "namuui-MacBookAir.local-1713971763"
#include "version.h"
#define REDIS_BUILD_ID_RAW SERVER_NAME VALKEY_VERSION REDIS_BUILD_ID REDIS_GIT_DIRTY REDIS_GIT_SHA1
